import { DocumentHead } from '@/components/DocumentHead';
import { TR_BRAND } from '@/lib/constants';
import { useSearch } from 'wouter';

export default function ReportAVerdict() {
  const searchString = useSearch();
  const searchParams = new URLSearchParams(searchString);
  const q = searchParams.get('q') || '';

  const pageTitle = `Report a wrong verdict | ${TR_BRAND}`;
  const pageDescription = `Flag an inaccurate or outdated Honest AI Consensus Verdict for review.`;

  const reportEmail = 'reports@truthrouter.ai';
  const mailtoSubject = encodeURIComponent(`Wrong verdict report${q ? ': ' + q : ''}`);
  const mailtoBody = encodeURIComponent(
    `Product / query: ${q ? q : '[paste the product name or comparison you searched]'}\n` +
    `What's wrong with the verdict: \n` +
    `Source that shows the correct information (link, if you have one): \n`
  );
  const mailtoHref = `mailto:${reportEmail}?subject=${mailtoSubject}&body=${mailtoBody}`;

  return (
    <main className="mx-auto w-full max-w-3xl px-5 pb-20 pt-14 sm:px-8">
      <DocumentHead title={pageTitle} description={pageDescription} />
      
      <p className="text-[13px] font-medium text-slate2">Legal</p>
      <h1 className="mt-2 font-display text-[36px] font-extrabold leading-[1.1] tracking-[-0.02em] sm:text-[44px]">Report a wrong verdict</h1>

      <div className="prose prose-slate mt-8 max-w-none prose-headings:font-display prose-headings:font-bold prose-p:leading-relaxed prose-p:text-slate2">
        <p>Verdicts are generated by an AI model reading public buyer opinion, and it can get things wrong — a spec, a price, a claim that's out of date. If you spot one, tell us and include a source if you have it.</p>
      </div>

      <div className="mt-8 rounded-2xl border border-ink/12 bg-surface p-6 sm:p-8">
        {q && (
          <>
            <p className="text-[13px] font-medium text-slate2">Reporting a verdict for</p>
            <p className="mt-1 font-display text-[22px] font-bold">{q}</p>
          </>
        )}
        <p className="mt-3 text-[15px] leading-relaxed text-slate2">Clicking the button below opens your email client with the details pre-filled. Add what's wrong and, if you have one, a link that shows the correct information.</p>
        <a href={mailtoHref} className="mt-5 inline-flex rounded-xl bg-ink px-6 py-3 text-[15px] font-semibold text-white transition-colors hover:bg-verdict">
          Open email to report it
        </a>
      </div>
    </main>
  );
}
