import { DocumentHead } from '@/components/DocumentHead';
import { TR_BRAND, TR_OWNER } from '@/lib/constants';
import { Link } from 'wouter';

export default function Terms() {
  const pageTitle = `Terms of use | ${TR_BRAND}`;
  const pageDescription = `The terms for using ${TR_BRAND}, including the limits of AI-generated verdicts.`;

  return (
    <main className="mx-auto w-full max-w-3xl px-5 pb-20 pt-14 sm:px-8">
      <DocumentHead title={pageTitle} description={pageDescription} />
      
      <p className="text-[13px] font-medium text-slate2">Legal</p>
      <h1 className="mt-2 font-display text-[36px] font-extrabold leading-[1.1] tracking-[-0.02em] sm:text-[44px]">Terms of use</h1>
      <p className="mt-3 text-[14px] text-slate2">Last updated {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>

      <div className="prose prose-slate mt-8 max-w-none prose-headings:font-display prose-headings:font-bold prose-p:leading-relaxed prose-p:text-slate2 prose-li:text-slate2">
        <p>By using {TR_BRAND}, operated by {TR_OWNER}, you agree to the following.</p>

        <h2>What the service is</h2>
        <p>{TR_BRAND} generates a research summary for a product name you enter, using an AI model that reads publicly available buyer opinion. It is a research aid, not professional purchase advice, not a warranty assessment, and not a substitute for checking current specifications, pricing and availability directly with a retailer or manufacturer.</p>

        <h2>Accuracy</h2>
        <p>Verdicts are generated by an AI model and may be incomplete, out of date, or simply wrong. {TR_OWNER} makes no guarantee of accuracy and is not liable for purchasing decisions made based on a verdict. If you spot an error, please use the <Link href="/report-a-verdict">report a wrong verdict</Link> page.</p>

        <h2>Fair use</h2>
        <p>The search is rate-limited per session to keep the service available to everyone. Automated scraping of verdicts at scale, or attempts to circumvent the rate limit, are not permitted.</p>

        <h2>Acceptable use</h2>
        <ul>
          <li>Do not submit queries designed to make the model produce unsafe, defamatory or unlawful content.</li>
          <li>Do not attempt to probe, disrupt or reverse engineer the underlying model or infrastructure.</li>
        </ul>

        <h2>Changes</h2>
        <p>These terms may be updated as the project changes. Continued use after an update means you accept the revised terms.</p>

        <h2>Contact</h2>
        <p>Questions about these terms can be sent through the channels listed on the <Link href="/press">press enquiries</Link> page.</p>
      </div>
    </main>
  );
}
